name: UDS App

on:
  push:
    branches: ["main"]
    tags:
      - 'v*'
  pull_request:
    branches: ["main"]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload artifact (JAR)
      uses: actions/upload-artifact@v4
      with:
        name: my-app-jar
        path: build/libs/*.jar

    - name: Create GitHub Release and attach artifact
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/libs/*.jar
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}